name: Multi-tenancy

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/multi-tenancy.yml"
      - "multi-tenancy/**"

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Set version
        id: set-version
        run: echo "::set-env name=PACKAGE_VERSION::$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER"

      - uses: actions/checkout@v2

      - name: Install Octopus CLI
        run: |
          sudo apt update && sudo apt install --no-install-recommends gnupg curl ca-certificates apt-transport-https && \
          curl -sSfL https://apt.octopus.com/public.key | sudo apt-key add - && \
          sudo sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" && \
          sudo apt update && sudo apt install octopuscli

      - name: Package multi-tenancy.rousseau.dev
        run: |
          mkdir -p ./packages/multi-tenancy.rousseau.dev/multi-tenancy/
          cp .firebaserc firebase.json ./packages/multi-tenancy.rousseau.dev/
          cp -avr ./multi-tenancy/* ./packages/multi-tenancy.rousseau.dev/multi-tenancy/
          octo pack --id="multi-tenancy.rousseau.dev" --format="Zip" --version="$PACKAGE_VERSION" --basePath="./packages/multi-tenancy.rousseau.dev" --outFolder="./packages"

      - name: Push multi-tenancy.rousseau.dev to Octopus
        run: octo push --package="./packages/multi-tenancy.rousseau.dev.$PACKAGE_VERSION.zip" --server="https://rousseau.octopus.app" --apiKey="${{ secrets.OCTOPUS_API_KEY }}"
